In [85]:
import pandas as pd
import glob

1-Importando a base de dados e juntando varias bases de dados da Leishmaniose

In [86]:
arquivos = glob.glob("LEIVA/*csv")

dfs = [
    pd.read_csv(arq, encoding="latin1", low_memory=False, sep=",")
    for arq in arquivos
]

df_total = pd.concat(dfs, ignore_index=True)

1.1-Mostrando a base de dados do SUS da doença Leishmaniose

In [87]:
df_total.head()

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,CS_ESCOLAR,NU_ANO,SEM_NOT,SG_UF_NOT,ID_REGIONA,DT_SIN_PRI,...,DS_TRANS_1,DT_DESLC2,DS_MUN_2,CO_UF_2,CO_PAIS_2,DS_TRANS_2,DT_DESLC3,DS_MUN_3,CO_UF_3,CO_PAIS_3
0,2926301,2601567.0,20000809,9.0,9.0,2000.0,322000.0,BA,2.0,20000102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2901502,2660229.0,20001122,4.0,3.0,2000.0,472000.0,BA,2.0,20001102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2910800,2799758.0,20001215,4.0,9.0,2000.0,502000.0,BA,2.0,20001215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2104552,2464659.0,20000810,4.0,6.0,2000.0,322000.0,MA,11.0,20000625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2105302,2456540.0,20001016,NaN,6.0,2000.0,422000.0,MA,11.0,20000720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
manter = ['DT_OBITO', 'EVOLUCAO', 'CS_GESTANT']

df_limpo = df_total.loc[
    :, (df_total.isna().mean() <= 0.15) | (df_total.columns.isin(manter))
]

In [89]:
df_limpo.head()

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,NU_ANO,SEM_NOT,SG_UF_NOT,DT_SIN_PRI,SEM_PRI,ANO_NASC,...,EMAGRA,TOSSE,BACO,FIGADO,HIV,IFI,OUTRO,CS_GESTANT,EVOLUCAO,DT_OBITO
0,2926301,2601567.0,20000809,9.0,2000.0,322000.0,BA,20000102,12000.0,1972.0,...,1.0,1.0,1.0,1.0,9.0,1.0,1.0,NaN,NaN,NaN
1,2901502,2660229.0,20001122,4.0,2000.0,472000.0,BA,20001102,442000.0,1984.0,...,2.0,2.0,1.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN
2,2910800,2799758.0,20001215,4.0,2000.0,502000.0,BA,20001215,502000.0,1958.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN
3,2104552,2464659.0,20000810,4.0,2000.0,322000.0,MA,20000625,262000.0,1998.0,...,1.0,2.0,1.0,1.0,2.0,3.0,3.0,NaN,NaN,NaN
4,2105302,2456540.0,20001016,NaN,2000.0,422000.0,MA,20000720,292000.0,1999.0,...,2.0,2.0,1.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN

In [90]:
df_limpo = df_limpo.drop(columns=['EMAGRA', 'TOSSE', 'BACO', 'FIGADO','IFI','OUTRO','ID_PAIS','FEBRE','FRAQUEZA'])

In [91]:
df_limpo.head()

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,NU_ANO,SEM_NOT,SG_UF_NOT,DT_SIN_PRI,SEM_PRI,ANO_NASC,CS_SEXO,ID_MN_RESI,SG_UF,HIV,CS_GESTANT,EVOLUCAO,DT_OBITO
0,2926301,2601567.0,20000809,9.0,2000.0,322000.0,BA,20000102,12000.0,1972.0,F,2926301.0,BA,9.0,NaN,NaN,NaN
1,2901502,2660229.0,20001122,4.0,2000.0,472000.0,BA,20001102,442000.0,1984.0,M,2901502.0,BA,2.0,NaN,NaN,NaN
2,2910800,2799758.0,20001215,4.0,2000.0,502000.0,BA,20001215,502000.0,1958.0,F,2908507.0,BA,9.0,NaN,NaN,NaN
3,2104552,2464659.0,20000810,4.0,2000.0,322000.0,MA,20000625,262000.0,1998.0,F,2104552.0,MA,2.0,NaN,NaN,NaN
4,2105302,2456540.0,20001016,NaN,2000.0,422000.0,MA,20000720,292000.0,1999.0,F,2105302.0,MA,2.0,NaN,NaN,NaN

In [ ]:
df_limpo['DT_OBITO'].value_counts()

DT_OBITO
            156504
20170508         9
20221221         8
20240610         8
20150226         7
             ...
20250714         1
20250626         1
20070203         1
20070310         1
20070213         1
Name: count, Length: 5018, dtype: int64

2-Descobrindo a linha onde começa o cabeçalho da base de dados?

In [ ]:
with open('CODIGO_IBGE.csv', encoding='latin1') as f:
    for i, linha in enumerate(f):
        if linha.startswith('UF,'):
            print(i, linha)
            break

6 UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Distrito,Código de Distrito Completo,Nome_Distrito,OBS,,Código de Distrito Completo,Nome_Distrito,,,,,,,,,

3-Descobrindo q é numero 6 onde começa o cabeçalho, fazendo a leitura e o tratamento dos dados

In [ ]:
df_ibge = pd.read_csv(
    'CODIGO_IBGE.csv',
    sep=',',
    encoding='latin1',
    skiprows=6,
    header=0,
    engine='python'
)

4-Mostrado as linhas e as colunas

In [ ]:
df_ibge.head()
df_ibge.columns

Index(['UF', 'Nome_UF', 'Região Geográfica Intermediária',
       'Nome Região Geográfica Intermediária', 'Região Geográfica Imediata',
       'Nome Região Geográfica Imediata', 'Município',
       'Código Município Completo', 'Nome_Município', 'Distrito',
       'Código de Distrito Completo', 'Nome_Distrito', 'OBS', 'Unnamed: 13',
       'Código de Distrito Completo.1', 'Nome_Distrito.1', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

5-Removendo todas as colunas Unnamed.

In [ ]:
df_ibge = df_ibge.loc[:, ~df_ibge.columns.str.startswith('Unnamed')]

6-Mostrando a base de dados de codigo Municipal do IBGE

In [ ]:
df_ibge.head()

,UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Distrito,Código de Distrito Completo,Nome_Distrito,OBS,Código de Distrito Completo.1,Nome_Distrito.1
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,5,110001505,Alta Floresta D'Oeste,NaN,110001505.0,Alta Floresta D'Oeste
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,15,110001515,Filadélfia d'Oeste,NaN,110001515.0,Filadélfia d'Oeste
2,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,20,110001520,Izidolândia,NaN,110001520.0,Izidolândia
3,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,25,110001525,Nova Gease d'Oeste,NaN,110001525.0,Nova Gease d'Oeste
4,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,30,110001530,Rolim de Moura do Guaporé,NaN,110001530.0,Rolim de Moura do Guaporé